version: '3.8'

services:
  chromadb:
    image: chromadb/chroma  # 최신 버전 사용 (원하는 버전이 있다면 명시적으로 지정 가능)
    container_name: chromadb_container
    ports:
      - "8000:8000"  # ChromaDB의 기본 포트
    environment:
      CHROMA_DB_PATH: /data  # 데이터 경로 설정 (필요시 설정)
    volumes:
      - chromadb_data:/data  # 데이터 볼륨 마운트

volumes:
  chromadb_data: